stages:
  preprocess:
    cmd: python preprocess.py
    deps:
    - data/diabetes.csv
    outs:
    - data/diabetes_processed.csv



  train:
    cmd: python train.py
    deps:
    - data/diabetes_processed.csv
    - train.py
    outs:
    - models/model.pkl
  evaluate:
    cmd: python evaluate.py
    deps:
    - data/diabetes_processed.csv
    - evaluate.py
    - models/model.pkl
    metrics:
    - metrics.json:
        cache: false
