stages:
  preprocess:
    cmd: python preprocess.py
    deps:
    - data/diabetes.csv
    outs:
    - data/diabetes_processed.csv
  train:
    cmd: python train.py
    deps:
    - data/diabetes_processed.csv
    outs:
    - model/diabetes_model.pkl
  evaluate:
    cmd: python evaluate.py
    deps:
    - data/diabetes_processed.csv
    - model/diabetes_model.pkl
